Final Review
elasticsearch-cn/kibana pull request #89
Opened 2018-05-08 07:54 UTC by howardhuanghua

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md)?
- If submitting code, have you included unit tests that cover the changes?
- If submitting code, have you tested and built your code locally prior to submission with `npm test && npm run build`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.

2018-05-08 09:28 UTC, node commented on docs/getting-started.asciidoc
> +在开始之前，请确保您<<install, 已安装 Kibana>> 并已成功<<connect-to-elasticsearch, 连接 Elasticsearch>> 。
连接 ->  连接至

2018-05-08 09:33 UTC, node commented on docs/getting-started/tutorial-load-dataset.asciidoc
> +有两个数据集是压缩文件。使用以下命令解压缩文件：
-> 其中有两个数据文件是压缩格式，可使用以下命令解压：

2018-05-08 11:52 UTC, node commented on docs/getting-started/tutorial-define-index.asciidoc
> +加载到 Elasticsearch 的每组数据都有一个索引模式（Index Pattern）。 在上一节中，为 Shakespeare 数据集创建了名为 `shakespeare` 的索引，为 accounts 数据集创建了名为 `bank` 的索引。一个 _索引模式_ 是可以匹配多个索引的带可选通配符的字符串。例如一般在通用日志记录中，一个典型的索引名称一般包含类似 YYYY.MM.DD 格式
shakespeare 参考前文统一翻译为中文 莎士比亚

2018-05-09 00:50 UTC, forearrow requested changes
提交我的22项comments

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +.简单的仪表盘
"Sample"非"Simple"

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +. 点击侧面导航中的 *Dashboard* 。您如果之前没有浏览过仪表盘，Kibana 会显示一个登陆页，在这个页面您可以点击 *+* 。如果没有这个页面，点击 *Dashboard* 返回登陆页。
此处的"Landing page"翻译成"登录页面"容易让人误解，建议翻译成"起始页面"

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +. 点击侧面导航中的 *Dashboard* 。您如果之前没有浏览过仪表盘，Kibana 会显示一个登陆页，在这个页面您可以点击 *+* 。如果没有这个页面，点击 *Dashboard* 返回登陆页。
这里的"Otherwise"不应该翻译成"如果没有这个页面"，原意不是"如果没有这个页面"，直接翻译成"否则"就ok

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +Kibana 在仪表盘容器中展示选中的可视化结果。如果您觉得容器展示的信息太小，您可以<<resizing-containers,调整容器大小>>。
这里也许翻译成这样更贴切一些："Kibana在仪表板上的容器中显示选定的可视化。 如果您看到容器太小的消息..."

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> += 仪表盘
建议将"Dashboard"翻译成"仪表板"而不是"仪表盘"

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +. 当您完成添加并整理好可视化结果后，点击 *Save* 来保存到仪表盘：
此处"arranging"可翻译成"排列"。"to save the dashboard"并非"save to the dashboard"，因此不应该翻译成"来保存到仪表板"。整句可翻译成："当您完成添加和排列可视化操作后，点击**保存**以保存仪表板。"

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +.. 为仪表盘取一个名字。
"Enter a name for the Dashboard"翻译成"为仪表板取一个名字"虽然不至于会让读者不明白要怎么做，但是这样翻译就失去原句的某些意思，建议翻译成"输入仪表板的名称"

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +.. 为仪表盘取一个名字。
如果是give a name for the dashboard才可以翻译成取名字

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +.. 点击 *Save* 按钮保存为 Kibana 保存项。
单击**保存**按钮将其存储为Kibana已保存的对象

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +.. 点击 *Save* 按钮保存为 Kibana 保存项。
尽量忠于原文愿意，尽量不要漏掉任何一个字句

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +. 鼠标悬停上方以显示容器控件。
这里省掉了必要的助词阅读起来会有点别扭，多加两个字变成：将鼠标悬停在上方以显示容器控件。
下面这一句“点击并长按容器右上角的移动按钮”在格式有问题，**Move**是加粗的界面中的文字，不用翻译，而且粗体格式被丢掉了

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +. 点击且长按容器右下角的 *Move* 按钮。
哪来的Move按钮？Resize按钮哪去了？

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +. 释放 *Move* 按钮。
同上

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +. 点击右上角 *Delete* 按钮。
“点击右上角 *Delete* 按钮”语句不通顺。。。我觉得我可以去做小学语文老师了:)

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +NOTE: 从仪表板删除可视化结果 _不会_ 删除保存可视化结果。
这一句容易让人有点摸不着头脑，建议翻译成："从仪表板中移除可视化 _不会_ 删除已保存的可视化。"

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +. 点击容器左下角的 *Expand* 按钮，这里会显示包含基础数据的表格。您也可以查看原始 的 JSON 格式的 Elasticsearch 请求和响应以及请求统计信息。请求统计信息显示查询持续时间、请求持续时间、匹配记录总数以及搜索的索引（或索引正则）。
"这里会显示包含基础数据的表格"改为"这将显示包含基础数据的表格"

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +将可视化数据以逗号分割值的形式导成（cvs）文件，点击数据表底部的 *Raw* 或者 *Formatted* 链接。 *Raw* 导出 Elasticsearch 存储格式的数据。 *Formatted* 导出格式化好的数据，详情参考<<managing-fields,field formatters>>。
要将可视化后的数据导出为逗号分隔值（CSV）文件，请点击数据表底部的 *Raw* 或 *Formatted* 链接。

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +将可视化数据以逗号分割值的形式导成（cvs）文件，点击数据表底部的 *Raw* 或者 *Formatted* 链接。 *Raw* 导出 Elasticsearch 存储格式的数据。 *Formatted* 导出格式化好的数据，详情参考<<managing-fields,field formatters>>。
少了前面这个“要”字，会让人多少产生一些误解

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> -Table. *Raw* exports the data as it is stored in Elasticsearch. *Formatted*
*Raw* exports the data as it is stored in Elasticsearch建议翻译成" *Raw* 原样输出存储在 Elasticsearch 中的数据"

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +TIP: 导入、导出和删除仪表盘，点击管理仪表盘链接打开 *Management/Kibana/Saved Objects/Dashboards* 。
问题1：**Manage Dashboards**不用翻译，而且必须加粗
问题2：少了开头的“To”，此篇翻译有很多地方都把前面的“To”给忽略了

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> -to view embedded dashboards.
请忠于原文，不要随意替换原文中的某些字词。
建议的翻译：您可以与其他用户共享Kibana仪表板的直接链接，也可以将仪表板嵌入到网页中。 用户必须具有Kibana访问权限才能查看嵌入式仪表板。

2018-05-09 00:50 UTC, forearrow commented on docs/dashboard.asciidoc
> +TIP: 当共享仪表盘快照链接的时候，请使用 *Short URL* 。 快照 URLs 很长会给 IE 用户或者其他工具带来麻烦。
每一句都尽量使用translate.google.cn去翻译，再人工纠正机器翻译的错误，这样翻译出来的结果更加专业，下面是谷歌翻译的结果：
在共享指向仪表板快照的链接时，请使用**Short URL**。 快照URL很长，对于Internet Explorer用户和其他工具可能会有问题。

2018-05-09 09:05 UTC, forearrow commented on docs/timelion.asciidoc
> +时序控件（Timelion）是一个基于时间序列的数据可视化工具，它可以将多种独立的数据源合并呈现到一张视图上。用户可以利用一些简单的表达式语言提取所需数据，并进行一些计算将复杂的问题简化并呈现结果。
Timelion 是一款时间序列数据可视化工具，可让您在单个可视化中将完全独立的数据源组合在一起。 它是由用于检索时间序列数据的简单表达式语言驱动的，执行计算以梳理出复杂问题的答案，并可视化结果。

2018-05-09 09:05 UTC, forearrow commented on docs/timelion.asciidoc
> +例如，Timelion 可以非常轻松的解决这些问题：
例如，Timelion 可以让您轻松获得如下问题的答案：

2018-05-09 09:05 UTC, forearrow commented on docs/timelion.asciidoc
> +* 过去某段时间页面的 UV 量是多少？
随着时间的推移，每个唯一用户查看了多少页？

2018-05-09 09:05 UTC, forearrow commented on docs/timelion.asciidoc
> +* 本站今天来自日本的访客占多少百分比？
日本百分之几的人口来到我的网站？

2018-05-09 09:05 UTC, forearrow commented on docs/timelion.asciidoc
> +* 标普500指数过去10天的移动平均值是多少？
标准普尔500指数的10日移动平均线是多少？

2018-05-09 09:05 UTC, forearrow commented on docs/timelion.asciidoc
> +* 过去两年所有的查询请求总量有多少？
过去2年内收到的所有搜索请求的累计总和是多少？

2018-05-09 09:05 UTC, forearrow commented on docs/timelion/timelion-getting-started.asciidoc
> +* <<timelion-save, 添加 Timelion 可视化控件到仪表盘>>
添加 Timelion 视图到仪表板

2018-05-09 09:05 UTC, forearrow commented on docs/timelion/timelion-getting-started.asciidoc
> +* <<timelion-inline-help, 查看内嵌的帮助文档>>
访问内嵌帮助和文档

2018-05-09 09:05 UTC, forearrow commented on docs/console.asciidoc
> +控制台可以解析像 cURL 命令这样的语句。例如下面这条控制台命令
控制台理解类似 cURL 语法的命令。 例如以下控制台命令

2018-05-09 09:05 UTC, forearrow commented on docs/console.asciidoc
> +就是一个简单的 Elasticsearch `_search API GET` 请求。下面是同样效果的 cURL 命令。
是 Elasticsearch 的 _search API 的简单 GET 请求

2018-05-12 12:38 UTC, howardhuanghua commented on docs/dashboard.asciidoc
> +.简单的仪表盘
这个错误点抓的尤为经典！

2018-05-12 12:46 UTC, howardhuanghua commented on docs/dashboard.asciidoc
> += 仪表盘
建议很好！

2018-05-12 13:41 UTC, howardhuanghua commented
comment updated for now.

2018-05-12 14:40 UTC, LennyZeng commented on docs/introduction.asciidoc
> +Kibana 是一款开源的数据分析和可视化平台，它是 Elastic Stack 成员之一，设计用于和 Elasticsearch 协作。您可以使用 Kibana 对 Elasticsearch 索引中的数据进行搜索、查看、交互操作。您可以很方便的利用平台化的图表、表格及地图对数据进行多元化的分析和呈现。
不需要"平台化"这个描述

2018-05-12 14:43 UTC, LennyZeng commented on docs/introduction.asciidoc
> +Kibana 可以使大数据通俗易懂。它很简单，基于浏览器的交互便于您快速创建和分享动态数据仪表盘来追踪 Elasticsearch 的实时数据变化。
“交互”应为“界面“

2018-05-12 14:54 UTC, LennyZeng commented on docs/setup.asciidoc
> +运行不同的 Kibana 和 Elasticsearch 补丁版本一般是支持的。因为我们鼓励用户去运行最新的补丁更新版本。
”一般是支持的“后面加一上”（比如：Kibana 5.0.0 和 Elasticsearch 5.0.1）“
第2句应该改为：”尽管我们鼓励用户在相同的补丁版本上运行Kibana和Elasticsearch“

2018-05-12 14:59 UTC, LennyZeng commented on docs/setup/install/targz.asciidoc
> +`.tar.gz` 整个包是独立的。默认情况下，所有的文件和目录都在 `$KIBANA_HOME` -- 解压包时创建的目录下。这样非常仿版，因为您不需要创建任何目录来使用 Kibana，卸载 Kibana 就是简单地删除 `$KIBANA_HOME` 目录。但还是建议修改一下配置文件和数据目录，这样就不会删除重要数据。
”仿版“改成”方便“

2018-05-12 15:08 UTC, LennyZeng commented on docs/setup/install/windows.asciidoc
> +使用 Kibana，卸载 Kibana 只需要简单的删除 `$KIBANA_HOME` 目录。但还是建议修改一下配置文件和数据目录，这样就不会删除重要数据。
这里不需要换行

2018-05-12 15:12 UTC, LennyZeng commented on docs/setup/settings.asciidoc
> +Kibana server 启动时从 `kibana.yml` 文件中读取配置属性。Kibana 默认配置 `localhost:5601` 。改变主机和端口号。或者连接其他机器上的 Elasticsearch，需要更新 `kibana.yml` 文件。也可以启用 SSL 和设置其他选项。
”改变主机和端口号“后号的句号改逗号

2018-05-12 15:35 UTC, LennyZeng commented on docs/setup/tribe.asciidoc
> +由于被使用集群的模糊性，Kibana 一些特性不可用：
换成”由于使用哪个集群会存在歧义“怎么样？

2018-05-13 00:29 UTC, icelengbing commented on docs/visualize.asciidoc
> +Kibana 可视化控件基于 Elasticsearch 的查询。利用一系列的 Elasticsearch {es-ref}search-aggregations.html[查询聚合]功能处理数据，然后利用一些图表来呈现您关心的数据趋势分布。
连续使用两个“利用”感觉不太顺畅，建议修改为：->

Kibana 可视化控件基于 Elasticsearch 的查询。利用一系列的 Elasticsearch {es-ref}search-aggregations.html[查询聚合]功能处理数据，您可以通过创建图表来呈现您关心的数据分布和趋势。

2018-05-13 00:34 UTC, icelengbing commented on docs/visualize.asciidoc
> +<<timelion-getting-started,Timelion>>:: 计算且合并多个时间序列数据集。
计算和合并来自多个时间序列的数据集。

2018-05-13 02:04 UTC, icelengbing commented on docs/visualize.asciidoc
> +注意：当从一个已有的搜索来构建可视化视图时，随后对已有查询的任何修改都会自动反馈在视图中。想要禁止自动更新的话，需要把视图从已保存的搜索断开连接。
NOTE: 当从一个已有的搜索来构建可视化视图时，随后对已有查询的任何修改都会自动反馈在视图中。想要禁止自动更新，您需要断开视图和已保存的搜索之间的连接。

2018-05-13 02:19 UTC, icelengbing commented on docs/visualize/y-axis-aggs.asciidoc
> +*Count*:: {es-ref}search-aggregations-metrics-valuecount-aggregation.html[_计数_] 聚合返回所选索引模式中元素的原始计数。
有个疑问：这里所有的聚合术语都有中文化翻译，而在pie-chart的翻译中所有聚合术语都直接应用英文，没有翻译。到底这些术语需要翻译吗？

*Count*:: {es-ref}search-aggregations-metrics-valuecount-aggregation.html[_计数_] 聚合返回所选索引模式中元素的原始数量。

2018-05-13 02:28 UTC, icelengbing commented on docs/visualize/y-axis-aggs.asciidoc
> +*Moving Average*:: {es-ref}search-aggregations-pipeline-movavg-aggregation.html[_移动平均值_] 聚合将滑动数据窗口并发出该窗口的平均值。
*Moving Average*:: {es-ref}search-aggregations-pipeline-movavg-aggregation.html[_移动平均值_] 聚合将动态移动数据窗口，生成该窗口数据的平均值。

2018-05-13 02:38 UTC, icelengbing commented on docs/visualize/x-axis-aggs.asciidoc
> +*Terms*:: {es-ref}search-aggregations-bucket-terms-aggregation.html[_terms_] 聚合使您可以指定要显示的给定字段的顶部或底部 _n_ 个元素，按数量或自定义指标进行排序。
*Terms*:: {es-ref}search-aggregations-bucket-terms-aggregation.html[_词条_] 聚合使您可以指定要显示的给定字段的顶部或底部 _n_ 个元素，按数量或自定义指标进行排序。

2018-05-13 04:27 UTC, icelengbing commented on docs/visualize/time-series-visual-builder.asciidoc
> +每个序列都支持一个标签，该标签将用于图例和标题，具体取决于所选的可视化类型。对于按词项分组的序列，可以指定 `{{key}}` 的 mustache 变量以替换该词项。对于大多数可视化，您还可以通过点击色板打开颜色选择器选择一种颜色。
这里的 {{key}} 原始英文页面就有显示问题。

2018-05-13 05:20 UTC, sdjnxj commented on docs/development/core/development-basepath.asciidoc
> +Kibana 开发服务器自动运行在一个有随机 `server.basePath` 的代理之后。这样，当开发者编写代码时，他们会不断地确认他们的代码是否与 basePath 一起工作。
是否应该翻译为：Kibana 开发服务器在一个有随机 server.basePath 的代理之后自动运行。

2018-05-13 05:21 UTC, sdjnxj commented on docs/plugins.asciidoc
> +您可以通过简单的指定插件名称来下载 Elastic 官方插件。也可以指定插件具体的 URL 来下载安装，例如：
您可以简单的通过指定插件名称来下载

2018-05-13 05:25 UTC, sdjnxj commented on docs/development/core/development-basepath.asciidoc
> +  - 从 `/{any}/app/{appName}` 重定向到 `/{randomBasePath}/app/{appName}` ，所以刷新会起作用
从而使刷新起作用

2018-05-13 05:26 UTC, sdjnxj commented on docs/plugins.asciidoc
> +如果插件使用了不同的用户安装且服务又没有跑起来，您就需要修改这些文件的所属用户：
如果插件使用了不同的用户安装且服务又没有运行起来

2018-05-13 05:28 UTC, sdjnxj commented on docs/plugins.asciidoc
> +您也可以通过手动删除 `plugins/` 目录下的对应的插件目录来删除插件。
您也可以通过手动删除 plugins/ 目录下的对应的插件目录来移除插件

2018-05-13 05:30 UTC, sdjnxj commented on docs/plugins.asciidoc
> +通过 `remove` 命令来删除插件：
如下例所示，您可以通过 remove 命令来移除插件：

2018-05-13 05:33 UTC, sdjnxj commented on docs/development/core/development-basepath.asciidoc
> +  - 代理所有到 Kibana 服务器并以 `/{randomBasePath}/` 开头的请求
将以 /{randomBasePath}/ 开头的所有请求代理到 Kibana 服务器

2018-05-13 05:40 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +在开发 Kibana 前端环境中使用的插件时，您可能想要包含一个或两个库（至少）。虽然这在90%的情况下都是很简单的，但总会有一些异常值，而其中一些异常值还是在非常受欢迎的项目中。
您可能想要包含（至少）一个或两个库。

2018-05-13 05:43 UTC, sdjnxj commented on docs/plugins.asciidoc
> +在 `install` 和 `remove` 命令中使用 `-c` 或者 `--config` 选项来指定启动 Kibana 启动的配置文件的路径。默认情况下，Kibana 使用 `config/kibana.yml` 配置文件。当您需要修改已安装好的插件配置时，使用 `bin/kibana-plugin` 命令来重启 Kibana 服务。当您使用自定义的配置文件时，每次使用 `bin/kiba
选项来指定启动 Kibana 的配置文件的路径

2018-05-13 05:47 UTC, sdjnxj commented on docs/plugins.asciidoc
> +=== 自定义插件及 Kibana 的配置
插件及自定义 Kibana 配置

2018-05-13 05:53 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +就像在 node.js 中一样，前端代码可以在不需要任何附件配置的情况下，使用 npm 安装节点模块。
就像在 node.js 中一样，前端代码无需进行扩展配置就能请求 npm 节点模块安装。

2018-05-13 05:57 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +# 下载您想用的库导该目录
将您想使用的库下载到该目录

2018-05-13 05:58 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +然后，像往常一样在您的 JavaScript 代码中包含包含该库：
多了一个“包含”

2018-05-13 06:02 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +一些 JavaScript 库声明它们依赖的方式，其他工具例如 webpack 并不理解。通常情况下，库不会导出它们提供的值，而只是将它们写入到全局变量里（或者某种意义上的变量）。
一些 JavaScript 库声明它们依赖的方式不会被诸如 webpack 的工具所理解。

2018-05-13 06:05 UTC, sdjnxj commented on docs/plugins/known-plugins.asciidoc
> +这个插件列表不保证适用于您的 Kibana 版本。不过它们是可以在 Kibana *5.x* 上正常工作。Kibana 安装程序将拒绝安装任何非针对您当前版本 Kibana 发布的插件。
将“非”改为“尚未”

2018-05-13 06:06 UTC, sdjnxj commented on docs/plugins/known-plugins.asciidoc
> +这个插件列表不保证适用于您的 Kibana 版本。不过它们是可以在 Kibana *5.x* 上正常工作。Kibana 安装程序将拒绝安装任何非针对您当前版本 Kibana 发布的插件。
不过它们是可以在 Kibana 5.x 上正常工作的。

2018-05-13 06:12 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +一些 JavaScript 库声明它们依赖的方式，其他工具例如 webpack 并不理解。通常情况下，库不会导出它们提供的值，而只是将它们写入到全局变量里（或者某种意义上的变量）。
（或者大致达到上述效果）。

2018-05-13 06:12 UTC, sdjnxj commented on docs/plugins/known-plugins.asciidoc
> +* https://github.com/fermiumlabs/mathlion[mathlion] (fermiumlabs) - 为 Timelion 增加方程解析和高数能力。
删除结尾的  。

2018-05-13 06:12 UTC, sdjnxj commented on docs/plugins/known-plugins.asciidoc
> +* https://github.com/nreese/kibana-time-plugin[Time picker as a dashboard panel] 在仪表板内可以查看和编辑时间范围的小组件
可以在仪表板内查看和编辑时间范围的小组件

2018-05-13 06:13 UTC, sdjnxj commented on docs/plugins/known-plugins.asciidoc
> +NOTE: 如果您希望将您的插件也添加到此页面，请打开 {repo}tree/{branch}/docs/plugins/known-plugins.asciidoc[pull request].
. 改为 。

2018-05-13 06:15 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +当将这样的代码拉入到 Kibana 中时，我们要编写 “桥接代码（shims）” 来整合第三方代码，以便与我们的应用、其他库和模块系统一起工作。我们可以使用 `webpackShims` 目录来做到这一点。
“桥接代码”（shims）

2018-05-13 06:19 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +通过例子，是解释如何编写桥接代码的最简单方式。下面是我们用于 jQuery 的 webpack 桥接代码。
示例是解释如何编写桥接代码的最简单方式。

2018-05-13 06:21 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +由于 `webpackShims` 的行为类似 `node_modules` ， 因此一旦 webpack 发现 `import 'jquery';` 语句，桥接代码会被加载。当它发生时，桥接代码会做两件事：
由于 `webpackShims` 的行为类似于 `node_modules` ， 一旦 webpack 发现 `import 'jquery';` 语句，桥接代码会被加载。

2018-05-13 06:28 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +. 最终，我们编写的 jQuery 插件被引入，因此每次在 jQuery 中导入文件，它会得到 jQuery 和 `$.findTestSubject` 帮助模块。
最终，我们编写的 jQuery 插件会被引入，因此每次有文件引入 jQuery 时，该文件会同时得到 jQuery 和 `$.findTestSubject` 的帮助模块。

2018-05-13 06:40 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +. 确保 jQuery 在 angular（实际运行在 shim 之上） 之前加载。
确保 jQuery 在 angular（实际运行上述的 shim ） 之前加载。

2018-05-13 06:44 UTC, sdjnxj commented on docs/development/core/development-dependencies.asciidoc
> +. 加载 angular-elastic 插件，每当我们导入 angular 时，都会要包含它。
加载 angular-elastic 插件，每次导入 angular 都需要包含 angular-elastic 插件。

2018-05-13 07:10 UTC, sdjnxj commented on docs/development/core/development-modules.asciidoc
> +    导入 Kibana 依赖却没有导入的 angular、一些 ui 服务和 “组件”。需要导入的全量列表被硬编码在模块中。希望这个列表会随着时间的推移而缩小，因为我们正确地映射出所需的模块并导入它们实际上是必要的。
随着我们正确地定位出所需模块并将其导入到需要他们的位置，这个列表可能会逐渐缩小。

2018-05-13 07:10 UTC, sdjnxj commented on docs/development/core/development-modules.asciidoc
> +  * 解析到下列路径中的第一个 **file** 是我们的匹配
下列路径中的第一个解析为一个 **file** 的是我们的匹配

2018-05-13 07:10 UTC, sdjnxj commented on docs/development/core/development-elasticsearch.asciidoc
> +Kibana 为和 elasticsearch 通信，在服务器和浏览器上提供了两种客户端。一种是用于管理 Kibana 状态的 'admin' 客户端，另一种是用于所有其他请求的 'data' 客户端。客户端使用 {ref}/client/javascript-api/current/index.html[elasticsearch.js library]。
这段翻译在 html 文档中不显示！

2018-05-13 07:23 UTC, sdjnxj commented on docs/development/plugin/development-uiexports.asciidoc
>  === UI Exports
Exports需要翻译么？

2018-05-13 07:26 UTC, sdjnxj commented on docs/development/plugin/development-uiexports.asciidoc
>  | Type | Purpose
类型 目的

2018-05-13 07:32 UTC, sdjnxj commented on docs/development/plugin/development-plugin-functional-tests.asciidoc
> -Plugins use the `FunctionalTestRunner` by running it out of the Kibana repo. Ensure that your Kibana Development Environment is setup properly before continuing.
Plugins use the `FunctionalTestRunner` by running it out of the Kibana repo. 这句译文不对，但我也没太看懂。

2018-05-13 07:37 UTC, sdjnxj commented on docs/development/plugin/development-plugin-functional-tests.asciidoc
> +插件通过运行 Kibana repo 使用 `FunctionalTestRunner` 。在继续之前，请确认您的 Kibana 开发环境配置正确。
插件在 Kibana repo 外部运行并使用 `FunctionalTestRunner` 。

2018-05-13 07:39 UTC, sdjnxj commented on docs/development/plugin/development-plugin-functional-tests.asciidoc
> +// 它确保返回带有项目配置值的对象
它返回带有项目配置值的对象

2018-05-13 07:41 UTC, sdjnxj commented on docs/development/plugin/development-plugin-functional-tests.asciidoc
> +    // 定义在您的测试中可用的服务和提供者，
提供程序

2018-05-13 07:43 UTC, sdjnxj commented on docs/development/plugin/development-plugin-functional-tests.asciidoc
> +    // 就像服务那样，PageObjects 定义为提供者的名称映射
提供程序

2018-05-13 07:44 UTC, sdjnxj commented on docs/development/plugin/development-plugin-functional-tests.asciidoc
> +    // 更多设置，例如 timeouts、 mochaOpts 等定义在配置模式。参加{blob}src/functional_test_runner/lib/config/schema.js[src/functional_test_runner/lib/config/schema.js]
参见

2018-05-13 07:46 UTC, sdjnxj commented on docs/development/plugin/development-plugin-functional-tests.asciidoc
> +现在可以在 repo 的根目录，运行您插件工程的 `FunctionalTestRunner` 脚本。
去掉逗号

2018-05-13 07:46 UTC, sdjnxj commented on docs/development/plugin/development-plugin-functional-tests.asciidoc
> +我们正在为这部分准备文档，但目前最好的资料是原始的 {pull}10359[pull request].
.改为。

2018-05-13 07:55 UTC, sdjnxj commented on docs/development/core/development-functional-tests.asciidoc
> +使用 node.js 执行 `FunctionalTestRunner` 脚本运行测试，使用 Kibana 的默认配置：
使用 node.js 执行 `FunctionalTestRunner` 脚本，以运行  Kibana 默认配置的测试：

2018-05-13 08:01 UTC, sdjnxj commented on docs/development/core/development-functional-tests.asciidoc
>  ==== Service Index
服务指标

2018-05-13 08:02 UTC, sdjnxj commented on docs/development/core/development-functional-tests.asciidoc
>  ===== Built-in Services
内置服务

2018-05-13 08:06 UTC, sdjnxj commented on docs/development/core/development-functional-tests.asciidoc
>  ===== Custom Services
客户服务
本篇文章中service多处未翻译。

2018-05-15 06:20 UTC, forearrow commented on docs/visualize/y-axis-aggs.asciidoc
> +*Count*:: {es-ref}search-aggregations-metrics-valuecount-aggregation.html[_计数_] 聚合返回所选索引模式中元素的原始计数。
好问题，我觉得开头加粗的Count不用翻译，后面的解析Count的文字可以翻译成中文

2018-05-15 07:47 UTC, forearrow reviewed
完成仪表板、时序控件、控制台的review

2018-05-15 07:47 UTC, forearrow commented on docs/console/multi-requests.asciidoc
> +控制台编辑器允许在彼此之下写多个请求，像在<<console-kibana>>章节展示中那样，您可以通过定位光标并使用<<action_menu,动作菜单>>向 Elasticsearch 提交请求。同样的您可以一次选择多个请求：
"控制台编辑器允许在彼此之下写多个请求"这一句有点费解，不过我也没有好的建议。只知道原文包含的意思是：控制台编辑器允许您编写彼此层叠的多个请求

2018-05-15 07:47 UTC, forearrow commented on docs/console/auto-formatting.asciidoc
> +控制台允许您自动格式复杂的请求，为此，请将光标置于您想格式化的请求上，并从操作菜单中选择自动缩进：
控制台允许您自动格式化格式凌乱的请求

2018-05-15 07:47 UTC, forearrow commented on docs/console/auto-formatting.asciidoc
> +控制台将调整请求的 JSON 体，之后请求会像图片所示：
控制台将调整请求的JSON体，现在看起来将是这样的：

2018-05-15 07:47 UTC, forearrow commented on docs/console/keyboard-shortcuts.asciidoc
> +Ctrl/Cmd + Alt + L:: 折叠或打开当前代码块。
折叠或展开当前代码块。

2018-05-15 07:47 UTC, forearrow commented on docs/console/keyboard-shortcuts.asciidoc
> +Ctrl/Cmd + Option + 0:: 折叠除当前代码块之外的所有代码块，通过添加 shift 打开除当前代码块之外的所有代码块。
折叠除当前代码块之外的所有代码块，通过添加 shift 来展开。

2018-05-15 07:47 UTC, forearrow commented on docs/console/keyboard-shortcuts.asciidoc
> +Down arrow:: 光标切换到自动补全菜单，使用方向键选择下一个选项。
将焦点切换到自动完成菜单。 使用箭头进一步选择一个选项。

2018-05-15 07:47 UTC, forearrow commented on docs/console/keyboard-shortcuts.asciidoc
> +Down arrow:: 光标切换到自动补全菜单，使用方向键选择下一个选项。
快捷键操作不一定有光标，原文中也说的是focus

2018-05-15 07:47 UTC, forearrow commented on docs/console/keyboard-shortcuts.asciidoc
> +=== 自动补全可见时
自动完成可见时

2018-05-15 07:47 UTC, forearrow commented on docs/console/keyboard-shortcuts.asciidoc
> +=== 自动补全可见时
如果决定将auto-complete翻译成自动完成，下文中出现auto-complete的地方也需要一并修改过来

2018-05-15 07:47 UTC, forearrow commented on docs/console/history.asciidoc
> +控制台会保留500条最新的被 Elasticsearch 成功执行的请求。历史记录可以通过点击窗口右上角的时钟图标来获得。这个图标会打开历史记录面板在那里您可以看到旧的请求。您也可以在这里选择一个请求，它将被添加到编辑器中当前光标所在的位置。
控制台维护 Elasticsearch 成功执行的最后500个请求的列表。 点击窗口右上角的时钟图标即可查看历史记录。这个图标会打开历史记录面板，您可以在其中查看旧请求。 您也可以在此处选择一个请求，它将被添加到编辑器中当前光标所在的位置。

2018-05-15 07:47 UTC, forearrow commented on docs/console/settings.asciidoc
> +控制台有很多设置，这些设置都可以在控制面板中找到。点击右上角的齿轮按钮就能打开设置面板。
控制台有多个可以设定的设置。 所有这些设置都可在设置面板中找到。 要打开面板，请点击右上角的齿轮图标。

2018-05-15 07:47 UTC, forearrow commented on docs/console/configuring-console.asciidoc
> +`console.enabled`:: *默认: true* 。设置为 false 来禁用控制台。切换这个配置服务器会在下次重启前重新生成资源，这样会导致页面渲染前可能有些延迟。
设置为 false 以禁用控制台。 切换此配置将导致服务器在下次启动时重新生成资源，这可能会造成页面开始服务之前有些延迟。

2018-05-18 06:49 UTC, merged